import turtle

# Pièce blanche
cavalier_BL = turtle.Turtle(shape='pieces/cavalier blanc.gif')
cavalier_BR = turtle.Turtle(shape='pieces/cavalier blanc.gif')
fou_BL = turtle.Turtle(shape='pieces/fou blanc.gif')
fou_BR = turtle.Turtle(shape='pieces/fou blanc.gif')
pion_B1 = turtle.Turtle(shape='pieces/pion blanc.gif')
pion_B2 = turtle.Turtle(shape='pieces/pion blanc.gif')
pion_B3 = turtle.Turtle(shape='pieces/pion blanc.gif')
pion_B4 = turtle.Turtle(shape='pieces/pion blanc.gif')
pion_B5 = turtle.Turtle(shape='pieces/pion blanc.gif')
pion_B6 = turtle.Turtle(shape='pieces/pion blanc.gif')
pion_B7 = turtle.Turtle(shape='pieces/pion blanc.gif')
pion_B8 = turtle.Turtle(shape='pieces/pion blanc.gif')
reine_B = turtle.Turtle(shape='pieces/reine blanc.gif')
roi_B = turtle.Turtle(shape='pieces/roi blanc.gif')
tour_BL = turtle.Turtle(shape='pieces/tour blanc.gif')
tour_BR = turtle.Turtle(shape='pieces/tour blanc.gif')

# Pièce noire
cavalier_NL = turtle.Turtle(shape='pieces/cavalier noir.gif')
cavalier_NR = turtle.Turtle(shape='pieces/cavalier noir.gif')
fou_NL = turtle.Turtle(shape='pieces/fou noir.gif')
fou_NR = turtle.Turtle(shape='pieces/fou noir.gif')
pion_N1 = turtle.Turtle(shape='pieces/pion noir.gif')
pion_N2 = turtle.Turtle(shape='pieces/pion noir.gif')
pion_N3 = turtle.Turtle(shape='pieces/pion noir.gif')
pion_N4 = turtle.Turtle(shape='pieces/pion noir.gif')
pion_N5 = turtle.Turtle(shape='pieces/pion noir.gif')
pion_N6 = turtle.Turtle(shape='pieces/pion noir.gif')
pion_N7 = turtle.Turtle(shape='pieces/pion noir.gif')
pion_N8 = turtle.Turtle(shape='pieces/pion noir.gif')
reine_N = turtle.Turtle(shape='pieces/reine noir.gif')
roi_N = turtle.Turtle(shape='pieces/roi noir.gif')
tour_NL = turtle.Turtle(shape='pieces/tour noir.gif')
tour_NR = turtle.Turtle(shape='pieces/tour noir.gif')
